server:
  port: 8081


management:
  health:
    redis:
      enabled: false
spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: simple_get_uuid_from_http_bin_when_path_contains_uuid_and_host_examplecom
          uri: https://httpbin.org
          predicates:
            - Path=/uuid
            - Host=**.example.com


        - id: get_uuid_from_http_bin_also_set_path_in_response
          uri: https://httpbin.org
          predicates:
            - Path=/demo
            - Host=**.example.com
          filters:
            - SetPath=/uuid

        - id: get_uuid_from_http_bin_using_dynamic_delays
          uri: https://httpbin.org
          predicates:
            - Path=/demo/{delay}/{stars}
            - Host=**.example.com
          filters:
            - SetPath=/drip
            - AddRequestParameter=duration,0
            - AddRequestParameter=numbytes,{stars}
            - AddRequestParameter=code,200
            - AddRequestParameter=delay,{delay}

        - id: weighted_routing_1
          uri: https://httpbin.org
          predicates:
            - Path=/wrouting/**
            - Weight=group1, 5
          filters:
            - SetPath=/drip
            - AddRequestParameter=duration,1
            - AddRequestParameter=numbytes,20
            - AddRequestParameter=code,200
            - AddRequestParameter=delay,1

        - id: weighted_routing_2
          uri: https://httpbin.org
          predicates:
            - Path=/wrouting/uuid
            - Weight=group1, 5
          filters:
            - SetPath=/uuid

        - id: using_circuit_breaker
          uri: https://httpbin.org
          predicates:
            - Path=/circuitbreaker/{delay}/{stars}
            - Host=**.example.com
          filters:
            - SetPath=/drip
            - AddRequestParameter=duration,0
            - AddRequestParameter=numbytes,{stars}
            - AddRequestParameter=code,200
            - AddRequestParameter=delay,{delay}
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/fallback

