server:
  port: 8081


management:
  health:
    redis:
      enabled: false
spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: get_uuid_from_http_bin
          uri: https://httpbin.org
          predicates:
            - Path=/uuid
            - Host=**.example.com


        - id: get_uuid_from_http_bin_also_set_path_in_response
          uri: https://httpbin.org
          predicates:
            - Path=/demo
            - Host=**.example.com
          filters:
            - SetPath=/uuid


        - id: get_uuid_from_http_bin_using_dynamic_delays
          uri: https://httpbin.org
          predicates:
            - Path=/demo
            - Host=**.example.com
          filters:
            - SetPath=/uuid
