spring:
  application:
    name: CircuitBreaker
management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: always
  health.circuitbreakers.enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 1
      slowCallDurationThreshold: 400
      permittedNumberOfCallsInHalfOpenState: 1
      automaticTransitionFromOpenToHalfOpenEnabled: true
      failureRateThreshold: 1
      slowCallRateThreshold: 1
      minimumNumberOfCalls: 1
      waitDurationInOpenState: 10000

